defaults: &environment
  working_directory: ~/n0s3p4ss
  docker:
    - image: circleci/python:3.7

version: 2
jobs:
  build:
    <<: *environment
    steps:
      - checkout
      - run:
          name: Building environment
          command: make install
  lint:
    <<: *environment
    steps:
      - checkout
      - run:
          name: Running linters and quality gate checkers
          command: make lint sonar_analysis
  test:
    <<: *environment
    steps:
      - checkout
      - run:
          name: Running unit tests
          command: make test


workflows:
  version: 2
  build-:
    jobs:
      - build:
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
