defaults: &environment
  working_directory: ~/nosepass
  docker:
    - image: circleci/python:3.7

version: 2
jobs:
  build:
    <<: *environment
    steps:
      - checkout
      - run:
          name: Building environment
          command: make install install_submodules install_sublist3r install_wafw00f
  lint:
    <<: *environment
    steps:
      - checkout
      - run:
          name: Running linters and quality gate checkers
          command: make lint sonar_scanner
  test:
    <<: *environment
    steps:
      - checkout
      - run:
          name: Running unit tests
          command: python3 -m unittest


workflows:
  version: 2
  build-:
    jobs:
      - build:
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
