version: 2.1

commands:
  docker-login:
    steps:
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

jobs:
  build:
    working_directory: ~/n0s3p4ss
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Building environment
          command: make install
      - save_cache:
          key: n0s3p4ss-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /home/circleci/.local/share/virtualenvs/
            - /home/circleci/n0s3p4ss/Sublist3r

  tests:
    working_directory: ~/n0s3p4ss
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - n0s3p4ss-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Running unit tests
          command: make test
      - run:
          name: Running linter
          command: make lint
      - run:
          name: Running coverage
          command: make coverage

  sonar:
    working_directory: ~/n0s3p4ss
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - docker-login
      - restore_cache:
          keys:
            - n0s3p4ss-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Sonarqube
          command: make sonar_analysis PROJECT_VERSION=$(git rev-parse --short HEAD)

workflows:
  version: 2
  build:
    jobs:
      - build
      - tests:
          requires:
            - build
      - sonar:
          context: docker-access
          requires:
            - build
          filters:
            branches:
              only:
                - master
